name: Maven Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify

      # Create staging directory
      - run: mkdir staging

      # Process module 1
      - run: mkdir staging/Backend && cp Backend/target/*.jar staging/Backend

      # Process module 2
      - run: mkdir staging/common && cp common/target/*.jar staging/common

      # Process module 3
      - run: mkdir staging/Frontend && cp Frontend/target/*.jar staging/Frontend

      # Upload artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging